os: osx
osx_image: xcode10.2

language: bash

before-install:
  -whoami
  -echo "Start of pipeline"
  -HOMEBREW_NO_AUTO_UPDATE=1
  
install:
  -whoami
  -echo "Start of the pipleine"
  -HOMEBREW_NO_AUTO_UPDATE=1

script:
  -ls
  -chmod +x hello.sh
  -./hello.sh
  
after-script:
  -echo "End of pipeline"
  

  
